### ISSUE TITLE
Filter Panel Frontend

### ISSUE THREAD

**Issue by RamtinTJB** [TritonSE/USHS-Housing-Portal#80]
# Overview

Develop the frontend for the V2 filter panel.

## Frontend

Refactor the old V1 filters and create new filter components that are only in V2. Also add a filter button on the bottom left corner that applies all the filters and calls the backend api

## Backend

N/A

## Acceptance Criteria
- [x] Refactor old filter components
- [x] Create new filter components
- [x] Filter button
- [x] Call the backend api on click

**Comment by petabite** [comment]
Closed by #90
